apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    run: titok
  name: titok
spec:
  replicas: 1
  selector:
    matchLabels:
      run: titok
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        run: titok
    spec:
      containers:
      - image: lalyos/12factor
        name: titok
        envFrom:
          - secretRef:
              name: szikret
        ports:
        - containerPort: 80
        resources: {}
status: {}
